-- ============================================================
-- 已执行过的列补全（记录，防止重复）
-- ============================================================
-- cicd_pipeline:
--   enable_canary, canary_replicas, canary_traffic_ratio,
--   canary_duration_sec, canary_auto_promote, canary_analysis_rules,
--   enable_deploy_silence, silence_buffer_minutes, silence_severities
-- cicd_pipeline_run:
--   workflow_name
-- ============================================================
